import re

CONTRACTIONS = [
    (re.compile("ain('|’)t", re.I), ["am not", "are not", "is not", "has not", "have not"]), 
    (re.compile("a lotta", re.I), ["a lot of"]), 
    (re.compile("betcha", re.I), ["bet you"]),
    (re.compile("lotsa", re.I), ["lots of"]), 
    (re.compile("are('|’)t", re.I), ["are not"]),
    (re.compile("can('|’)t", re.I), ["cannot"]),
    (re.compile("c('|’)mon", re.I), ["come on"]),
    (re.compile("couldja", re.I), ["could you"]),
    (re.compile("couldn('|’)t", re.I), ["could not"]),
    (re.compile("coulda",re.I), ["could have"]),
    (re.compile("cuppa", re.I), ["cup of"]), 
    (re.compile("cuz", re.I), ["because"]),
    (re.compile("('|’)cos", re.I), ["because"]),
    (re.compile("('|’)coz", re.I), ["because"]),
    (re.compile("('|’)cause", re.I), ["because"]), 
    (re.compile("d('|’)you", re.I), ["do you"]),
    (re.compile("didn('|’)t", re.I), ["did not"]),
    (re.compile("didn('|’)tcha", re.I), ["did not you"]),
    (re.compile("doesn('|’)t", re.I), ["does not"]),
    (re.compile("don('|’)t", re.I), ["do not"]),
    (re.compile("didja", re.I), ["did you"]),
    (re.compile("dontcha", re.I), ["do not you"]),
    (re.compile("dunno", re.I), ["do not know"]),
    (re.compile("hadn('|’)t", re.I), ["had not"]),
    (re.compile("hasn('|’)t", re.I), ["has not"]),
    (re.compile("haven('|’)t", re.I), ["have not"]),
    (re.compile("hadn('|’)t", re.I), ["he had", "he would"]),
    (re.compile("he('|’)ll", re.I), ["he will", "he shall"]),
    (re.compile("he('|’)s", re.I), ["he is", "he has"]),
    (re.compile("How('|’)s", re.I), ["How is"]),
    (re.compile("howdja", re.I), [" how did you"]), 
    (re.compile("I('|’)d", re.I), ["I had", "I would"]),
    (re.compile("I('|’)ll", re.I), ["I will", "I shall"]),
    (re.compile("I('|’)m", re.I), ["I am"]),
    (re.compile("I('|’)ve", re.I), ["I have"]),
    (re.compile("isn('|’)t", re.I), ["is not"]),
    (re.compile("it('|’)s", re.I), ["it is"]),
    (re.compile("let('|’)s", re.I), ["let us"]),
    (re.compile("kinda", re.I) ,  ["kind of"]), 
    (re.compile("lemme", re.I), ["let me"]), 
    (re.compile("gimme", re.I) ,  ["give me"]),
    (re.compile("gonna", re.I), ["going to"]),
    (re.compile("gotta", re.I), ["got to","got a"]),
    (re.compile("gotcha", re.I), ["got you"]),
    (re.compile("mightn('|’)t", re.I), ["might not"]),
    (re.compile("mustn('|’)t", re.I), ["must not"]),
    (re.compile("mucha", re.I), ["much of"]),
    (re.compile("needn('|’)t", re.I), ["need not"]),
    (re.compile("oughta",re.I), ["ought to"]), 
    (re.compile("oughtn('|’)t", re.I), ["ought not"]),
    (re.compile("outta", re.I), ["out of"]),
    (re.compile("shan('|’)t", re.I), ["shall not"]),
    (re.compile("she('|’)d", re.I), ["she had", "she would"]),
    (re.compile("she('|’)s", re.I), ["she is", "she has"]),
    (re.compile("she('|’)da", re.I), ["she would have"]),
    (re.compile("shouldn('|’)t", re.I), ["should not"]),
    (re.compile("shoulda", re.I), ["should have"]),
    (re.compile("sorta", re.I), ["sort of "]),
    (re.compile("s('|’)more", re.I), ["some more"]),
    (re.compile("tell('|’)em", re.I), ["tell them"]),
    (re.compile("that('|’)s", re.I), ["that is", "that has"]),
    (re.compile("there('|’)s", re.I), ["there is", "there has"]),
    (re.compile("they('|’)d", re.I), ["they had", "they would"]),
    (re.compile("they('|’)ll", re.I), ["they will", "they shall"]),
    (re.compile("they('|’)re", re.I), ["they are"]),
    (re.compile("wanna", re.I), ["want to","want a"]),
    (re.compile("we('|’)d", re.I), ["we had", "we would"]),
    (re.compile("we('|’)re", re.I), ["we are"]),
    (re.compile("we('|’)ve", re.I), ["we have"]),
    (re.compile("were('|’)t", re.I), ["were not"]),
    (re.compile("whatcha", re.I), ["what a(re.you", "what have you"]),
    (re.compile("what('|’)ll", re.I), ["what will", "what shall"]),
    (re.compile("what('|’)re", re.I), ["what are"]),
    (re.compile("what('|’)s", re.I), ["what is", "what has"]),
    (re.compile("what('|’)ve", re.I), ["what have"]),
    (re.compile("when('|’)s", re.I), ["when is"]),
    (re.compile("where('|’)s", re.I), ["where is", "where has"]),
    (re.compile("who('|’)d", re.I), ["who had", "who would"]),
    (re.compile("who('|’)ll", re.I), ["who will", "who shall"]),
    (re.compile("who('|’)re", re.I), ["who are"]),
    (re.compile("who('|’)s", re.I), ["who is", "who has"]),
    (re.compile("who('|’)ve", re.I), ["who have"]),
    (re.compile("why('|’)s", re.I), ["why is"]),
    (re.compile("won('|’)t", re.I), ["will not"]),
    (re.compile("wontcha", re.I), ["will not you"]),
    (re.compile("wouldn('|’)t", re.I), ["would not"]),
    (re.compile("woulda", re.I), ["would have"]),
    (re.compile("wouldja", re.I), ["would you"]), 
    (re.compile("whadaya", re.I), ["what do you"]), 
    (re.compile("whereja", re.I), ["where did you"]), 
    (re.compile("whadja", re.I), ["what did you"]),
    (re.compile("ya", re.I), ["you"]),
    (re.compile("y('|’)", re.I), ["you"]),
    (re.compile("you('|’)d", re.I), ["you had", "you would"]),
    (re.compile("you('|’)ll", re.I), ["you will", "you shall"]),
    (re.compile("you('|’)re", re.I), ["you are"]),
    (re.compile("you('|’)ve", re.I), ["you have"])
]

'''
needa   need to 
hafta/hasta have to / has to    
init    isn’t it    
useta   used to .
supposeta   supposed to 
'''


           
        


